<a href="https://colab.research.google.com/github/lyhstat/Python_ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

In [ ]:
import numpy as np

In [ ]:
#陣列
a0 = np.arange(5)
print(a0)
a1 = np.arange(1,6,2)
print(a1)
a = np.array([1,2,3])
print(a)
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
print(b)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
print(c)

[0 1 2 3 4]
[1 3 5]
[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [ ]:
a2 = np.zeros(2)
print(a2)
a3 = np.zeros((3,4))
print(a3)
a4 = np.ones((2,3,4),dtype=np.int16)
print(a4)
a5 = np.linspace(0,2,9) #evenly spaced values
print(a5)
d = np.random.random((2,2)) #array with random values
print(d)
e = np.full((2,2),7) #Constant array
print(e)
f = np.eye(2) #I2X2 identity matrix
print(f)

[0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[[0.77663918 0.79413581]
 [0.57776616 0.35548254]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


In [ ]:
a.shape #Array dimensions

(3,)

In [ ]:
len(a) #Length of array

3

In [ ]:
b.ndim #Number of array dimensions

2

In [ ]:
e.size #Number of array elements

4

In [ ]:
b.dtype #Data type of array elements

dtype('float64')

In [ ]:
b.dtype.name #Name of data type

'float64'

In [ ]:
g = a - b #np.subtract(a,b)
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
a + b #np.add(a,b)
a / b #np.divide(a,b)
a * b #np.multiply(a,b)
np.exp(b)
np.sqrt(b)
np.sin(a)
np.cos(b)
np.log(a)
e.dot(f) #e @ f 內積

array([[7., 7.],
       [7., 7.]])

In [ ]:
a==2

array([False,  True, False])

In [ ]:
a<2

array([ True, False, False])

In [ ]:
a.sum()
a.min()
b.max(axis=0) #Maximum value of an array row
b.cumsum(axis=1) #Cumulative sum of the elements 累加
a.mean()
b.median()
a.corrcoef()
np.std(b)

In [ ]:
h = a.view()
np.copy(a)
h = a.copy()
h

array([1, 2, 3])

In [ ]:
a.sort()
c.sort(axis=0)
a6=np.array([(3,2,9),(5,8,6)])
a6.sort(axis=0)
a6

array([[3, 2, 6],
       [5, 8, 9]])

In [ ]:
a[2]

3

In [ ]:
b[1,2]

6.0

In [ ]:
a[0:2] #0 到索引 2（不包括 2）

array([1, 2])

In [ ]:
b[0:2,1]

array([2., 5.])

In [ ]:
b[:1] #第一列 b[0:1, :]

array([[1.5, 2. , 3. ]])

In [ ]:
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

In [ ]:
c[1,...] # [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [ ]:
a[ : :-1]  #反矩陣

array([3, 2, 1])

In [ ]:
a[a<2]

array([1])

In [ ]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [ ]:
i = np.transpose(b) #反矩陣
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [ ]:
i.T  #轉置

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
b.ravel()  #Flatten the array

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [ ]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [ ]:
h

array([1, 2, 3])

In [ ]:
np.append(h,g)  #附加

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [ ]:
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [ ]:
np.delete(a,[1])

array([1, 3])

In [ ]:
d = np.arange(10,25,5) #10,15,20
np.concatenate((a,d),axis=0) #連接

array([ 1,  2,  3, 10, 15, 20])

In [ ]:
np.vstack((a,b))  #堆疊

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
#陣列維度轉換(一維轉二維)
aa = np.arange(16)
print(aa)
bb= aa.reshape((4,4))
print(bb)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  # 計算均值
matrix = np.random.rand(3, 3)
print(np.linalg.inv(matrix))  # 矩陣求逆
import pandas as pd
df = pd.read_csv("data.csv")
df.fillna(0, inplace=True)  # 填補缺失值
df['new_feature'] = df['feature1'] / df['feature2']  # 創建新特徵
summary = df.groupby('category').mean()  # 分組並計算平均值
print(summary)
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf = RandomForestClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"模型準確度: {accuracy}")
